version: '3.8'

services:
  backend:
    image: tribui1912/hospital-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=hospital_db
      - SECRET_KEY=your_secret_key_here
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=30
      - OPENAI_API_KEY=your_openai_api_key_here
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: tribui1912/hospital-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=hospital_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d hospital_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
